
# Feed Forward 
__1. All nodes are fully connected.__<br>
__2. Activation flows from input layer to output, without back loops.__ <Br>
__3. There is one layer between input.__<Br>
__4. [Towards Data Science Blog BY Andrew Tch for neural networks details ](https://towardsdatascience.com/the-mostly-complete-chart-of-neural-networks-explained-3fb6f2367464).__


### Titanic Dataset is used to implement Feed Forward
[Download Titanic Dataset](https://www.kaggle.com/c/titanic/data).


In [253]:
import numpy as np 
import pandas as pd
from keras import models
from keras import layers

In [272]:
def reading_test_train_data():
    train = pd.read_csv('./datasets/train.csv')
    test = pd.read_csv('./datasets/test.csv')
    return train,test


def adding_title_using_name(dataset):
    """
    Fetching Mr,Miss,Mrs title from name 
    """ 
    dataset['Title'] = dataset['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)
    dataset['Title'] = dataset['Title'].replace('Mlle', 'Miss')
    dataset['Title'] = dataset['Title'].replace('Ms', 'Miss')
    dataset['Title'] = dataset['Title'].replace('Mme', 'Mrs')
    return dataset


def converting_title_to_int(title):
    """
    Assigning Number to each title
    """
    title= title.strip().lower()
    if title == 'mr':
        return 1
    elif title =='miss':
        return 2
    elif title =='mrs':
        return 3
    else:
        return 0
    
def age_into_grp(dataset):
    """
    converting age into age_group as bins
    """
    bins = [0,11,18,22,27,33,40,66, 120]
    labels = [str(i) for i in range(1,len(bins))]
    dataset['Age'] = pd.cut(dataset['Age'], bins, labels = labels,include_lowest = True)
    return dataset

###  Create feed forward neural network to train data

In [255]:
def feed_foward_model(number_of_features):
    # Start neural network
    model = models.Sequential()

    # Add fully connected layer with a ReLU activation function
    model.add(layers.Dense(units=16, activation='relu', input_shape=(number_of_features,)))

    # Add fully connected layer with a ReLU activation function
    model.add(layers.Dense(units=16, activation='relu'))

    # Add fully connected layer with a sigmoid activation function
    model.add(layers.Dense(units=1, activation='sigmoid'))
    
    return model

In [257]:
train,test = reading_test_train_data()


In [258]:
# first 10 rows
train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [259]:
# 891 rows 
# 12 columns /featurs including target
train.shape

(891, 12)

In [260]:
# only age count() is less then total df len means contains nan values
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

###  Manipulating --- AGE 

In [261]:
# filling age with age median
train['Age'] = train['Age'].fillna(train['Age'].median())

### ADDING NEW FEATURE 

In [262]:
# check who came with family or who came alone
train['with_family'] = train['SibSp'] + train['Parch']
train.loc[train['with_family'] > 0, 'not_alone'] = 0
train.loc[train['with_family'] == 0, 'not_alone'] = 1
train['not_alone'] = train['not_alone'].astype(int)
train.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  with_family  not_alone  
0      0         A/5 21171   7.2500   NaN        S            1          0  
1      0          PC 17599  71.2833   C85        C            1          0  
2      0  STON/O2. 3101282   7.9250   NaN        S            0          1  
3      0            113803  53.1000  C123        S            1          0  
4      0            373450   8.0500   NaN        S            0          1

### Filling Embarked column

In [263]:
# checking Embarked data stats
train['Embarked'].describe()

count     889
unique      3
top         S
freq      644
Name: Embarked, dtype: object

In [264]:
train['Embarked'] = train['Embarked'].fillna('S')

In [265]:

train['Embarked'] = train['Embarked'].astype('category').cat.codes

### Manipulating FARE

In [266]:
train['Fare'].describe() 
train['Fare'] = train['Fare'].astype(int)

### Manipulating GENDER feature

In [267]:
train['Sex'].unique()

array(['male', 'female'], dtype=object)

In [268]:
train['Sex'] = train['Sex'].astype('category').cat.codes
train['Sex'].unique()

array([1, 0], dtype=int64)

### Manipulating Name and extracting Title from it
#### Then Converting them into category

In [269]:
train = adding_title_using_name(train)


In [270]:
train['Title'] = train['Title'].apply(converting_title_to_int)

In [271]:
train['Title'].unique()

array([1, 3, 2, 0], dtype=int64)

## converting age into bins - range

In [273]:
train = age_into_grp(train)

In [274]:
train['Age'].value_counts()

5    303
7    143
4    106
6    101
3     92
2     71
1     68
8      7
Name: Age, dtype: int64

In [275]:
train.drop(['PassengerId','Name','Ticket','Cabin'],axis=1,inplace=True)

In [276]:
train.head()

Survived  Pclass  Sex Age  SibSp  Parch  Fare  Embarked  with_family  \
0         0       3    1   3      1      0     7         2            1   
1         1       1    0   6      1      0    71         0            1   
2         1       3    0   4      0      0     7         2            0   
3         1       1    0   6      1      0    53         2            1   
4         0       3    1   6      0      0     8         2            0   

   not_alone  Title  
0          0      1  
1          0      3  
2          1      2  
3          0      3  
4          1      1

## HANDLING TEST DATA AND PREPARING IT


In [277]:
# viewing test dataset
test.head(10)

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
5          897       3                    Svensson, Mr. Johan Cervin    male   
6          898       3                          Connolly, Miss. Kate  female   
7          899       2                  Caldwell, Mr. Albert Francis    male   
8          900       3     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female   
9          901       3                       Davies, Mr. John Samuel    male   

    Age  SibSp  Parch     Ticket     Fare Cabin Embarked  
0  34.5      0      0     330911   7.8292   NaN        Q  
1  47.0      1      0     363272   7.0000   NaN        S  
2  62.0      0      0     240276   9.6875   NaN        Q  
3  27.0      0      0     315154   8.6625   NaN        S  
4  22.0      1      1    3101298  12.2875   NaN        S  
5  14.0      0      0       7538   9.2250   NaN        S  
6  30.0      0      0     330972   7.6292   NaN        Q  
7  26.0      1      1     248738  29.0000   NaN        S  
8  18.0      0      0       2657   7.2292   NaN        C  
9  21.0      2      0  A/4 48871  24.1500   NaN        S

In [278]:
test.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

### Manipulting age for test dataset

In [279]:
# filling age with age median
test['Age'] = test['Age'].fillna(test['Age'].median())

### Creating With_familt and not_alone feature

In [280]:
train.isna().any()

Survived       False
Pclass         False
Sex            False
Age            False
SibSp          False
Parch          False
Fare           False
Embarked       False
with_family    False
not_alone      False
Title          False
dtype: bool

In [281]:
# check who came with family or who came alone
test['with_family'] = test['SibSp'] + test['Parch']
test.loc[test['with_family'] > 0, 'not_alone'] = 0
test.loc[test['with_family'] == 0, 'not_alone'] = 1
test['not_alone'] = test['not_alone'].astype(int)
test.head(5)

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  with_family  not_alone  
0  34.5      0      0   330911   7.8292   NaN        Q            0          1  
1  47.0      1      0   363272   7.0000   NaN        S            1          0  
2  62.0      0      0   240276   9.6875   NaN        Q            0          1  
3  27.0      0      0   315154   8.6625   NaN        S            0          1  
4  22.0      1      1  3101298  12.2875   NaN        S            2          0

### Filling Embarked column in test dataset

In [282]:
# checking Embarked data stats
test['Embarked'].describe()

count     418
unique      3
top         S
freq      270
Name: Embarked, dtype: object

In [283]:
test['Embarked'] = test['Embarked'].fillna('S')
test['Embarked'] = test['Embarked'].astype('category').cat.codes

### Manipulating FARE  in test dataset

In [284]:
test['Fare'].describe() 
test['Fare'] = train['Fare'].astype(int)

### Manipulating gender feature in test dataset

In [285]:
test['Sex'] = test['Sex'].astype('category').cat.codes
test['Sex'].unique()

array([1, 0], dtype=int64)

### Manipulating Name and extracting Title from it in test dataset
#### Then Converting them into category

In [286]:
test = adding_title_using_name(test)
test['Title'] = test['Title'].apply(converting_title_to_int)
test['Title'].unique()

array([1, 3, 2, 0], dtype=int64)

### converting age into bins

In [287]:
test = age_into_grp(test)
test.head()

PassengerId  Pclass                                          Name  Sex Age  \
0          892       3                              Kelly, Mr. James    1   6   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    0   7   
2          894       2                     Myles, Mr. Thomas Francis    1   7   
3          895       3                              Wirz, Mr. Albert    1   4   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    0   3   

   SibSp  Parch   Ticket  Fare Cabin  Embarked  with_family  not_alone  Title  
0      0      0   330911     7   NaN         1            0          1      1  
1      1      0   363272    71   NaN         2            1          0      3  
2      0      0   240276     7   NaN         1            0          1      1  
3      0      0   315154    53   NaN         2            0          1      1  
4      1      1  3101298     8   NaN         2            2          0      3

In [288]:
test.drop(['Name','Ticket','Cabin'],axis=1,inplace=True)

In [289]:
passengerId_test = test['PassengerId']

In [290]:
test.drop(['PassengerId'],axis=1,inplace=True)

In [291]:
train.dropna(inplace=True)
y_train = train['Survived']

In [292]:
train.drop(['Survived'],axis=1,inplace=True)

In [293]:
network = feed_foward_model(len(test.columns))
network.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])# Accuracy performance metric

In [294]:
#Fitting the data to the training dataset
network.fit(train,y_train, batch_size=10, epochs=300)

Epoch 1/300
891/891 [==============================] - 2s 3ms/step - loss: 1.4320 - acc: 0.6240
Epoch 2/300
891/891 [==============================] - 0s 224us/step - loss: 0.6364 - acc: 0.6768
Epoch 3/300
891/891 [==============================] - 0s 184us/step - loss: 0.6120 - acc: 0.6914
Epoch 4/300
891/891 [==============================] - 0s 182us/step - loss: 0.5822 - acc: 0.7329
Epoch 5/300
891/891 [==============================] - 0s 189us/step - loss: 0.5632 - acc: 0.7340
Epoch 6/300
891/891 [==============================] - 0s 218us/step - loss: 0.5545 - acc: 0.7407
Epoch 7/300
891/891 [==============================] - 0s 190us/step - loss: 0.5445 - acc: 0.7475
Epoch 8/300
891/891 [==============================] - 0s 180us/step - loss: 0.5329 - acc: 0.7632
Epoch 9/300
891/891 [==============================] - 0s 183us/step - loss: 0.5330 - acc: 0.7733
Epoch 10/300
891/891 [==============================] - 0s 181us/step - loss: 0.4976 - acc: 0.7767
Epoch 11/300
891/891 

891/891 [==============================] - 0s 165us/step - loss: 0.4290 - acc: 0.8081
Epoch 84/300
891/891 [==============================] - 0s 193us/step - loss: 0.4308 - acc: 0.8137
Epoch 85/300
891/891 [==============================] - 0s 170us/step - loss: 0.4178 - acc: 0.8126
Epoch 86/300
891/891 [==============================] - 0s 166us/step - loss: 0.4299 - acc: 0.8159
Epoch 87/300
891/891 [==============================] - 0s 211us/step - loss: 0.4211 - acc: 0.8092
Epoch 88/300
891/891 [==============================] - 0s 166us/step - loss: 0.4197 - acc: 0.8114
Epoch 89/300
891/891 [==============================] - 0s 174us/step - loss: 0.4307 - acc: 0.8103
Epoch 90/300
891/891 [==============================] - 0s 178us/step - loss: 0.4235 - acc: 0.8081
Epoch 91/300
891/891 [==============================] - 0s 167us/step - loss: 0.4379 - acc: 0.7946
Epoch 92/300
891/891 [==============================] - 0s 172us/step - loss: 0.4177 - acc: 0.8159
Epoch 93/300
891/891 [=

891/891 [==============================] - 0s 209us/step - loss: 0.4072 - acc: 0.8283
Epoch 165/300
891/891 [==============================] - 0s 220us/step - loss: 0.4193 - acc: 0.8260
Epoch 166/300
891/891 [==============================] - 0s 206us/step - loss: 0.4205 - acc: 0.8137
Epoch 167/300
891/891 [==============================] - 0s 204us/step - loss: 0.3997 - acc: 0.8339
Epoch 168/300
891/891 [==============================] - 0s 214us/step - loss: 0.3990 - acc: 0.8260
Epoch 169/300
891/891 [==============================] - 0s 197us/step - loss: 0.3984 - acc: 0.8182
Epoch 170/300
891/891 [==============================] - 0s 201us/step - loss: 0.4013 - acc: 0.8238
Epoch 171/300
891/891 [==============================] - 0s 248us/step - loss: 0.4058 - acc: 0.8305
Epoch 172/300
891/891 [==============================] - 0s 197us/step - loss: 0.3980 - acc: 0.8238
Epoch 173/300
891/891 [==============================] - 0s 203us/step - loss: 0.4310 - acc: 0.8182
Epoch 174/300


891/891 [==============================] - 0s 196us/step - loss: 0.3994 - acc: 0.8283
Epoch 246/300
891/891 [==============================] - 0s 237us/step - loss: 0.3913 - acc: 0.8294
Epoch 247/300
891/891 [==============================] - 0s 193us/step - loss: 0.4049 - acc: 0.8260
Epoch 248/300
891/891 [==============================] - 0s 192us/step - loss: 0.3931 - acc: 0.8215
Epoch 249/300
891/891 [==============================] - 0s 194us/step - loss: 0.3885 - acc: 0.8384
Epoch 250/300
891/891 [==============================] - 0s 193us/step - loss: 0.3926 - acc: 0.8339
Epoch 251/300
891/891 [==============================] - 0s 189us/step - loss: 0.4031 - acc: 0.8272
Epoch 252/300
891/891 [==============================] - 0s 244us/step - loss: 0.3958 - acc: 0.8260
Epoch 253/300
891/891 [==============================] - 0s 204us/step - loss: 0.4076 - acc: 0.8283
Epoch 254/300
891/891 [==============================] - 0s 269us/step - loss: 0.3935 - acc: 0.8305
Epoch 255/300


In [295]:
model_evaluation=network.evaluate(train, y_train)
model_evaluation

891/891 [==============================] - 0s 213us/step


[0.37854867720376495, 0.8383838379155639]

In [296]:
y_pred=network.predict(test)
y_pred =(y_pred>0.5)

In [297]:
result = pd.DataFrame()

In [298]:
result['PassengerId'] = passengerId_test

In [299]:
result['Survived'] = y_pred

In [300]:
result['Survived'] = np.where(result['Survived'] == False,0,1)

In [301]:
result.to_csv("./datasets/results.csv",index=False)